# Generated by Django 2.2.10 on 2020-08-19 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cat',
            new_name='category',
        ),
    ]
