# Generated by Django 2.2.10 on 2020-08-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200818_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='cat',
        ),
        migrations.AlterField(
            model_name='image',
            name='added_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
