# Generated by Django 2.2.10 on 2020-08-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200818_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
